# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

shared:
  api_key: 123

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0e7a7d1b1b7750c851c7f10efdb00d1b0366bbbc6df22ac16cf6739fce64e869a1158fbfa340f6b7148e5b381156d85ea6d3a6b15215c7e7a5c4132fa55d80ba

test:
  secret_key_base: 0cae7497dd9e4e1966a2c4530c0201e1bb533059b103dffb77da331803b1cbca9717930434be70dc4a350836e2994a8ad4c29fed06c644ad329a5c0ac2f8c2de

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
